"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

format = '''
[╭──](fg:208) [ $directory$rust$package$git_branch ](bg:238)[](fg:238) $fill $time [──╮](fg:208) 
[│](fg:208)[│$fill││](fg:208) 
[╰──](fg:208) $character
'''

right_format = '[──╯](fg:208)'

[character]
success_symbol = '[ \$ ](fg:green bg:237)[](fg:237)'
error_symbol = '[ \$ ](fg:red bg:237)[](fg:237)'

[directory]
style = 'bold cyan bg:238'
format = '[$path ](bold cyan bg:238)[$read_only](red)'

[rust]
style = 'bold bg:238'
format = '[ ](fg:238 bg:240)[$symbol($version )](bold bg:240)'

[package]
format = '[ ](fg:240 bg:239)[$symbol$version ](bold bg:239)'

[git_branch]
style = 'bg:238'
format = '[ ](fg:239 bg:238)[$symbol$branch(:$remote_branch)](bold bg:238)'

# TODO: SETUP TIME
[time]
format = "[](fg:238)[ $time ](bg:238)"
time_format = "%T"
disabled = false

[fill]
style = 'fg:240'
symbol = ' '
